### ISSUE TITLE
PHP 8.3

### ISSUE THREAD

**Issue by fritzdacat** [krausandre/wsm-form-spamshield#11]
Hello, according to composer.json the extension is only ready for "php": ">=7.0,<8.3". What about support for PHP 8.3?

**Comment by krausandre** [comment]
Hi, good hint. I will check that immediately and update the composer.json. Thx for reporting.

**Comment by krausandre** [comment]
I updated the PHP version dependency to ">=7.0,<8.4" and had some tests. Works well on my side. Would you please also check if it works in your environment?
