### ISSUE TITLE
Identifier 'form' has already been declared

### ISSUE THREAD

**Issue by weisgerberm** [krausandre/wsm-form-spamshield#13]
Hi, 
i'm getting this error when I load my form in frontend. It prevents my form to be send.

Uncaught SyntaxError: Identifier 'form' has already been declared (at form-security-check.js?1712844855:1:1)

I guess it has a name conflict with another js file where a variable named "form" exists. Maybe you could scope the code or rename it?

**Comment by krausandre** [comment]
Hi @weisgerberm,

thank you very much for that hint.

I just updated the JavaScript to scope the variables.

Maybe you can also have a try on it. 

Best regards.

**Comment by weisgerberm** [comment]
Hi @krausandre 

It works, thanks for the quick fix!
