### ISSUE TITLE
Validator is executed twice

### ISSUE THREAD

**Issue by webian** [krausandre/wsm-form-spamshield#7]
https://github.com/krausandre/wsm-form-spamshield/blob/b1957898deb22d22144daab6fc8e8faaa4a092c3/Classes/Mvc/Validation/SecureCheckValidator.php#L52
it seems that the validator is executed twice when the field is setup like mentioned here: [securityLevel](https://github.com/krausandre/wsm-form-spamshield/blob/b1957898deb22d22144daab6fc8e8faaa4a092c3/README.rst#how-to-use)

If I omit the validators setup and leave only type, identifier and label then the validator is executed only once with values for securityLevel and formTimeout from: https://github.com/krausandre/wsm-form-spamshield/blob/b1957898deb22d22144daab6fc8e8faaa4a092c3/Classes/Mvc/Validation/SecureCheckValidator.php#L58
and next 3 lines that set useful values

Instead, with the full mentioned setup, the validator is executed twice, once with "useful values" and once with the values set in the formdefinition.

**Comment by krausandre** [comment]
Hi Christian! :)
Yes this is a known issue, which I (and some others) investigated quite some time on it. Thank you for the hint, for debugging it and bring up the behaviour insights. If you have an idea how to fix it, let me know. 

I will still go on to find out what go wrong here...

**Comment by webian** [comment]
Hi André! :)
In my use cases it works by simply omitting the validators setting and leaving only type, identifier and label.
But I am not sure if this will cause problems in other use cases.

If you need more information please ask.

Thanks for this extension, really good captcha replacement!

**Comment by webian** [comment]
Oh yes, I remember now, sorry... the problem with my "solution" is that by removing the validators setting, you cannot customize securityLevel and formTimeout.

In my use cases the defaults are fine, but they may not be correct in other use cases.

Perhaps moving the setting of securityLevel and formTimeout out of the validators setup can solve the problem?

**Comment by krausandre** [comment]
Thank you very much, cool that you like the extension! 👍 

This sounds like a workaround to me, but to solve the problem quickly, it might work for now.

I will check this, and also check if existing forms still can work after this change. It would be nice, if the existing once do not break afterwards. 😆

**Comment by sneopu** [comment]
I made some tests. It seems it can be fixed by removing following lines:
https://github.com/krausandre/wsm-form-spamshield/blob/1ab44d1974906b2aa972294c3aacaa8a213c2810/Configuration/Yaml/FormElements/SecureCheck.yaml#L85-L87

Can you confirm this?

**Comment by krausandre** [comment]
@sneopu sorry for being late! 
I had a try on your suggestion and I think this is a good approach. Thank you very much for your feedback.
I will have some tests over the different PHP versions and TYPO3 version and will publish this ASAP.
