### ISSUE TITLE
Availability for other Extensions?

### ISSUE THREAD

**Issue by mtness** [krausandre/wsm-form-spamshield#9]
Hi there,
first of all, thank you so much for this extension, it just works as intended and saves us a lot of headache.

Would it be possible to use this spamshield for extension-generated forms, too ?

Thanks in advance and best regards,
MT

**Comment by krausandre** [comment]
Hi @mtness, 
I would expect it to work like mentioned here:
https://docs.typo3.org/c/typo3/cms-form/main/en-us/I/Concepts/FrontendRendering/Index.html

But I didn't tried it on my own and didn't understand your concrete use case or what you are going to do.

Do you want to use it generated by a PHP Class, by TypoScript, or do you want to generate the form in your fluid template?
I think it should work like other form fields too. But if not, let me know. Would be glad to hear about your experience and what exactly didn't work.


Edit: Or are you talking about fluid forms wihtout formframework?
https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/typo3/fluid/latest/Form.html

**Comment by mtness** [comment]
Good Morning @krausandre,

my usecase is this one:
We are using the reserve-extension for appointments - but recently these forms have been discovered by the bots
and we are showered with spam :/

Since this extension uses fluid-geneated forms, I need to find a way to use the spamshield with them.

Best regards and thank you,
MT

**Comment by krausandre** [comment]
Good Morning @mtness,

if you write your own extension, you can simply take the code and add it to your extension. The hidden field, the JavaScript, and add the validator logic to your controller or a validator class. Those are the three components you need. 

For other extensions, this not that easy to do. Maybe you can easily add the hidden field and JavaScript to the templates by overwriting them, but to add the validation to the controller, you have to overwrite the controller and the Domain/Model class to add a validation. This is not the way it works with EXT:form, but could be a workaround.

Fluid templates are mostly easy to overwrite, just add them via typoscript to the templateRootPaths with an higher priority. In a fluid template, you can add JavaScript via the AssetCollector.

To overwrite the Controller class, here are some infos how to do so:

Sometimes, you can simply extend the original class and then use dependency injection:
https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/DependencyInjection/Index.html#dependency-injection-in-a-xclassed-class

Somtimes, you need maybe to XCLASS the Controller:
https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/Xclasses/Index.html#xclasses

Another way could be to ask the developer of the extension to add some spam protection.


But I don't know how to generally add the validation and the partial to all fluid forms of any extension. I think this is not possible.

**Comment by mtness** [comment]
Hi @krausandre ,
Thank you for all these details!
Ok, I will (have to) go the fast way first and add the code to the corresponding extension - 
But in order to find a more general solution here, I will do brainstorming with some colleagues.

Thank you very much, best regards and merry christmas!
MT
